"""Global application configuration loader with XDG path resolution."""

import os
from functools import lru_cache
from pathlib import Path
from typing import Optional

import yaml

from ..errors import ConfigError
from .global_schema import GlobalConfig


# ---------------------------------------------------------------------------
# Path resolution
# ---------------------------------------------------------------------------


def get_config_dir() -> Path:
    """Return the XDG config directory for Elasticity.

    Resolution order:
    1. ``ELASTICITY_CONFIG`` env var (parent directory of the config file)
    2. ``XDG_CONFIG_HOME/elasticity/``
    3. ``~/.config/elasticity/``
    """
    env_path = os.environ.get("ELASTICITY_CONFIG")
    if env_path:
        return Path(env_path).expanduser().parent

    xdg_config_home = os.environ.get("XDG_CONFIG_HOME")
    if xdg_config_home:
        return Path(xdg_config_home).expanduser() / "elasticity"

    return Path.home() / ".config" / "elasticity"


def get_global_config_path() -> Path:
    """Return the resolved path to the global config file.

    Resolution order:
    1. ``ELASTICITY_CONFIG`` env var (used as-is)
    2. ``XDG_CONFIG_HOME/elasticity/config.yaml``
    3. ``~/.config/elasticity/config.yaml``
    """
    env_path = os.environ.get("ELASTICITY_CONFIG")
    if env_path:
        return Path(env_path).expanduser()

    return get_config_dir() / "config.yaml"


def get_data_dir() -> Path:
    """Return the XDG data directory for Elasticity.

    Resolution order:
    1. ``ELASTICITY_DATA_DIR`` env var
    2. ``XDG_DATA_HOME/elasticity/``
    3. ``~/.local/share/elasticity/``
    """
    env_path = os.environ.get("ELASTICITY_DATA_DIR")
    if env_path:
        return Path(env_path).expanduser()

    xdg_data_home = os.environ.get("XDG_DATA_HOME")
    if xdg_data_home:
        return Path(xdg_data_home).expanduser() / "elasticity"

    return Path.home() / ".local" / "share" / "elasticity"


# ---------------------------------------------------------------------------
# Loader
# ---------------------------------------------------------------------------


@lru_cache(maxsize=1)
def load_global_config(config_path: Optional[str] = None) -> GlobalConfig:
    """Load and validate the global configuration file.

    If the file does not exist, ``GlobalConfig`` defaults are returned
    (the global config file is optional). An explicit ``config_path``
    bypasses the normal path resolution; this is used by tests and the
    ``elasticity config`` CLI commands.

    The result is cached after the first call. To reload (e.g. in tests),
    call ``load_global_config.cache_clear()`` first.

    Args:
        config_path: Optional explicit path; ``None`` uses
            :func:`get_global_config_path`.

    Raises:
        ConfigError: If the file exists but cannot be parsed or fails
            schema validation.
    """
    path = Path(config_path).expanduser() if config_path else get_global_config_path()

    if not path.exists():
        return GlobalConfig()

    try:
        with open(path, "r") as f:
            data = yaml.safe_load(f)
    except yaml.YAMLError as e:
        raise ConfigError(f"Invalid YAML in global config {path}: {e}") from e
    except OSError as e:
        raise ConfigError(f"Error reading global config {path}: {e}") from e

    if data is None:
        return GlobalConfig()

    try:
        return GlobalConfig.model_validate(data)
    except Exception as e:
        raise ConfigError(f"Invalid global configuration in {path}: {e}") from e


def get_default_global_config_yaml() -> str:
    """Return a commented YAML template for the global config file."""
    return """\
# Elasticity global configuration
# Generated by: elasticity config init
#
# This file configures application-level settings shared across all
# orchestrations. For orchestration-specific settings (agent types,
# tools, flows), use per-project YAML files.

# Sandbox / execution environment
sandbox:
  # Execution provider. Options: local (default), docker, daytona
  provider: local
  # Provider-specific settings (varies by provider)
  # settings:
  #   image: python:3.12-slim

# Storage paths
storage:
  # Path to SQLite session database.
  # Default: ~/.local/share/elasticity/sessions.db
  # session_db: /custom/path/to/sessions.db

# Logging
logging:
  # Chat log file path, or false to disable.
  # Default: ~/.local/share/elasticity/chat.log
  # chat_log: /custom/path/to/chat.log
  # chat_log: false

# Global MCP servers available to all orchestrations.
# Per-orchestration mcp_servers take precedence on name conflicts.
# mcp_servers:
#   filesystem:
#     command: ["npx", "-y", "@modelcontextprotocol/server-filesystem", "."]
#     transport: stdio
"""
